# Generated by Django 2.0.2 on 2018-04-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeployHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'SUCCESS'), (1, 'FAIL'), (2, 'UNKNOWN')])),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_code', models.CharField(max_length=20)),
                ('server_type', models.CharField(choices=[('CLIENT', 'CLIENT'), ('OWN', 'OWN'), ('OTHER', 'OTHER')], max_length=10)),
                ('server_name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('gitrepo', models.CharField(max_length=100)),
                ('lastcontrol', models.DateTimeField()),
                ('status', models.BooleanField(choices=[(0, 'PASSED'), (1, 'ERROR')])),
                ('build_version', models.CharField(max_length=20)),
                ('on_revision', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SourcesTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('source_build_version', models.CharField(max_length=20)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=50)),
                ('url_target', models.CharField(max_length=100)),
                ('client_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('server_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Server')),
                ('sources_group', models.ManyToManyField(through='app.SourcesTargets', to='app.Source')),
            ],
        ),
        migrations.AddField(
            model_name='sourcestargets',
            name='target_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Target'),
        ),
        migrations.AddField(
            model_name='deployhistory',
            name='target_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Target'),
        ),
    ]
