# Generated by Django 2.0.2 on 2018-04-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcestargets',
            name='source_build',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='build_version',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='lastcontrol',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sourcestargets',
            name='source_build_version',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
