# Generated by Django 2.0.2 on 2018-06-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180531_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(db_index=True, max_length=20)),
                ('create_datetime', models.DateTimeField()),
                ('source_build_version', models.CharField(max_length=20)),
                ('source_build', models.FileField(upload_to='')),
                ('stage', models.IntegerField(choices=[(0, 'QA'), (1, 'Canary'), (2, 'Deploy')])),
                ('closed', models.BooleanField()),
                ('next_stage_datetime_set', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sourcestargets',
            name='source_build',
        ),
        migrations.AlterField(
            model_name='source',
            name='gitrepo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
