# Generated by Django 2.0.2 on 2018-06-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180531_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='internal_teamcity_build',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='target_type',
            field=models.IntegerField(choices=[(0, 'QA'), (1, 'Canary'), (2, 'Normal')], default=2),
        ),
        migrations.AddField(
            model_name='update',
            name='internal_teamcity_build',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='update',
            name='stage',
            field=models.IntegerField(choices=[(0, 'QA'), (1, 'Canary'), (2, 'Deploy')], default=0),
        ),
    ]
