# Generated by Django 2.0.2 on 2018-06-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180601_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(default='test', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='target',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='scriptdir_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='source_build',
            field=models.FileField(upload_to='builds/%Y/'),
        ),
    ]
